// store
export const SET_OUTPUT_STORE_PROPERTY = 'SET_OUTPUT_STORE_PROPERTY';
export const REMOVE_OUTPUT_STORE_PROPERTY = 'REMOVE_OUTPUT_STORE_PROPERTY';
export const SET_OUTPUT_STORE_WARNING = 'SET_STORE_WARNING';
export const TOGGLE_EDIT_MODAL = 'TOGGLE_EDIT_MODAL';

// actions
export const CREATE_NEW_OUTPUT_ACTION = 'CREATE_NEW_ACTION';
export const EDIT_OUTPUT_ACTION_TYPE = 'EDIT_ACTION_TYPE';
export const EDIT_OUTPUT_ACTION_NAME = 'EDIT_ACTION_NAME';
export const EDIT_OUTPUT_ACTION_TARGET = 'EDIT_ACTION_TARGET';
export const EDIT_OUTPUT_ACTION_VALID = 'EDIT_ACTION_VALID';
export const REMOVE_OUTPUT_ACTION = 'REMOVE_ACTION';

// components
export const SELECT_COMPONENT = 'SELECT_COMPONENT';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const REMOVE_COMPONENT = 'REMOVE_COMPONENT';
export const ADD_CHILD_COMPONENT = 'ADD_CHILD_COMPONENT';
export const REMOVE_CHILD_COMPONENT = 'REMOVE_CHILD_COMPONENT';

// component props
export const TOGGLE_COMPONENT_CONNECTION = 'TOGGLE_COMPONENT_CONNECTION';
export const BIND_ACTION_TO_COMPONENT = 'BIND_ACTION_TO_COMPONENT';
export const REMOVE_ACTION_FROM_COMPONENT = 'REMOVE_ACTION_FROM_COMPONENT';
export const BIND_STORE_PROP_TO_COMPONENT = 'BIND_STORE_PROP_TO_COMPONENT';
export const REMOVE_STORE_PROP_FROM_COMPONENT = 'REMOVE_STORE_PROP_FROM_COMPONENT';
