// store
export const SET_OUTPUT_STORE = 'SET_STORE';
export const SET_OUTPUT_STORE_WARNING = 'SET_STORE_WARNING';

// actions
export const CREATE_NEW_OUTPUT_ACTION = 'CREATE_NEW_ACTION';
export const EDIT_OUTPUT_ACTION_TYPE = 'EDIT_ACTION_TYPE';
export const EDIT_OUTPUT_ACTION_NAME = 'EDIT_ACTION_NAME';
export const EDIT_OUTPUT_ACTION_TARGET = 'EDIT_ACTION_TARGET';
export const EDIT_OUTPUT_ACTION_VALID = 'EDIT_ACTION_VALID';
export const REMOVE_OUTPUT_ACTION = 'REMOVE_ACTION';

// components
export const SELECT_COMPONENT = 'SELECT_COMPONENT';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const REMOVE_COMPONENT = 'REMOVE_COMPONENT';
export const SPECIFY_CHILD_COMPONENT = 'SPECIFY_CHILD_COMPONENT';
